services:
  db:
    build:
      context: .
      dockerfile: docker/postgres/Dockerfile
    ports:
      - 5432:5432
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    profiles:
      - app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db
    restart: unless-stopped
    env_file:
      - .env

volumes:
  pgdata:
    external: true
    name: the-bluer-book-db
