services:
  db:
    build:
      context: .
      dockerfile: docker/postgres/Dockerfile
    ports:
      - 5432:5432
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    external: true
    name: the-bluer-book-db
