{{- if .Values.backup.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-backup-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-backup
    app.kubernetes.io/name: {{ .Chart.Name }}-backup
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.backup.storage.storageClass }}
  resources:
    requests:
      storage: {{ .Values.backup.storage.size }}
{{- end }}
