{{- if .Values.mcp.ingress.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}-mcp
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}-mcp
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`{{ .Values.mcp.ingress.host }}`)
    kind: Rule
    services:
    - name: {{ .Release.Name }}-mcp
      port: {{ .Values.mcp.service.port }}
{{- end }}
