# PostgreSQL configuration
postgresql:
  enabled: true
  image:
    repository: postgres
    tag: "17.5-alpine"
  persistence:
    enabled: true
    size: 1Gi
    storageClass: local-path
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "250m"

# Application configuration
app:
  replicaCount: 1
  image:
    repository: ghcr.io/kieranajp/the-bluer-book
    tag: latest
  service:
    port: 8080
    type: ClusterIP
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "250m"

ingress:
  enabled: true
  host: "recipes.kieranajp.uk"
  middlewares:
    - google-auth

secretName: bluer-book-secrets
secrets:
  DB_USER: "bluer_book"
  DB_PASS: "xxx"
  DB_NAME: "bluer_book"
  DB_HOST: "bluer-book-postgresql"
  DB_PORT: "5432"
